PRODUCT_PROPERTY_OVERRIDES +=  \
    10.0.0.(02AE) \
    aaudio.mmap_exclusive_policy = 2 \
    aaudio.mmap_policy = 2 \
    bastet.service.enable=true \
    dalvik.vm.checkjni=false \
    dalvik.vm.dex2oat-threads=4 \
    dalvik.vm.heapgrowthlimit=384m \
    dalvik.vm.heapmaxfree=8m \
    dalvik.vm.heapminfree=2m \
    dalvik.vm.heapsize=512m \
    dalvik.vm.heapstartsize=8m \
    dalvik.vm.heaptargetutilization=0.75 \
    dalvik.vm.image-dex2oat-threads=4 \
    debug.sf.disable_backpressure = 1 \
    debug.sf.latch_unsignaled = 1 \
    hw.lcd.density=480 \
    keyguard.no_require_sim=true \
    persist.kirin.media.hires.enable=true \
    persist.kirin.media.lowlatency.enable=true \
    persist.kirin.media.offload.enable=true \
    persist.kirin.media.usbvoice.enable=true \
    persist.kirin.media.usbvoice.name=USB-Audio - HUAWEI GLASS \
    persist.kirin.touch_move_opt = 1 \
    persist.kirin.touch_vsync_opt = 1 \
    persist.kirin.touchevent_opt = 1 \
    persist.sys.jankenable=true \
    ro.board.platform=kirin710 \
    ro.bt.bdaddr_path=/data/vendor/bluedroid/macbt \
    ro.carrier=unknown \
    ro.comp.chipset_version=Chipset-miami 10.0.0.(02AE) \
    ro.config.hiaiversion=000.000.000.000 \
    ro.config.hw_navigationbar=true \
    ro.config.hw_volte_on=true \
    ro.control_privapp_permissions=enforce \
    ro.kirin.config.hw_board_ipa = true \
    ro.kirin.config.hw_perfgenius = true \
    ro.kirin.product.platform=kirin710 \
    ro.netflix.bsp_rev=KIRIN710-15488-1 \
    ro.opengles.version=196610 \
    ro.product.board=kirin710 \
    ro.product.vendor.brand=kirin710 \
    ro.product.vendor.device=kirin710 \
    ro.product.vendor.manufacturer=HUAWEI \
    ro.product.vendor.model=kirin710 \
    ro.product.vendor.name=kirin710 \
    ro.sf.lcd_density=480 \
    ro.vendor.build.display.id=Chipset-miami \
    ro.vendor.build.id=QP1A.190711.020 \
    ro.vendor.build.tags=release-keys \
    ro.vendor.build.type=user \
    ro.vendor.build.version.incremental=20191210030358 \
    ro.vendor.config.hw_music_lp=true \
    ro.vendor.config.music_lp_vol=true \
    ro.vendor.treble.data_violator.disable=true \
    ro.vendor.tui.service=true \
    ro.vendor.vndk.version=26.0.0 \
    use_sensorhub_labc=false \
    vendor.debug.config.mmu_en=1 \
